### PR TITLE
Custom okteto patches

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
This PR adds okteto's patches on top of moby's `v0.10.3` latest tag

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Update on the bug tracking: I could not reproduce the same error mentioned before.
Though, I'm hitting some errors that seem related to the `rootless` mode, and I think that's why I cannot reproduce them while on `okteto up`.

Here are some of the logs of an error I get:

```
time="2022-06-10T16:41:45Z" level=warning msg="failed to remove directory" error="unlinkat /home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2774/fs/tmp/yarn--1654710024891-0.17669622874088153: operation not permitted" path=/home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2774
time="2022-06-10T16:41:45Z" level=warning msg="failed to remove directory" error="unlinkat /home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2757/fs/tmp/yarn--1654709983253-0.32017927013231184: operation not permitted" path=/home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2757
time="2022-06-10T16:46:20Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = process \"/bin/sh -c go install github.com/codegangsta/gin@latest &&     go install github.com/go-delve/delve/cmd/dlv@latest &&     go install golang.org/x/tools/gopls@latest &&     curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/bin\" did not complete successfully: exit code: 1\n"
time="2022-06-10T16:46:21Z" level=warning msg="failed to remove directory" error="unlinkat /home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2774/fs/tmp/yarn--1654710024891-0.17669622874088153: operation not permitted" path=/home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2774
time="2022-06-10T16:46:21Z" level=warning msg="failed to remove directory" error="unlinkat /home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2757/fs/tmp/yarn--1654709983253-0.32017927013231184: operation not permitted" path=/home/user/.local/share/buildkit/runc-overlayfs/snapshots/snapshots/2757
```

**Comment by AgustinRamiroDiaz** [comment]
Update: Seems like switching between `rootless` and `root` has lead to a problem with caching. 

With the prod version I am getting now this error:
```
#7 [dev 3/8] RUN go install github.com/go-delve/delve/cmd/dlv@latest &&     curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/bin
#7 CACHED
#8 [dev 4/8] WORKDIR /usr/src/app
#8 ERROR: mkdir /home/user/.local/tmp/buildkit-mount992494693/usr/src/app: operation not permitted
```

Seems like step 7 is skipped due to it being cached, but actually it is not and thus the error. Checking into the container with `kubectl exec -it agustin-okteto-enterprise-buildkit-0 -- sh` I can see this:
```
/ # ls /home/user/.local/tmp/
buildkit-mount006293331  rootlesskit734443466
```

The `buildkit-mount992494693` is not present in the file system.

**Comment by AgustinRamiroDiaz** [comment]
Update: I was able to clear buildkit's cache and I'm back to where I started. Deploying movies throws this:
```
 Error building image 'registry.agustin.dev.okteto.net/delta/movies-api:4f2d96a4caf5ed665cb76cc9e113de5e939ab38b2ee6e172568321e1c45865bc': build failed: failed to solve: failed to read dockerfile: snapshot  does not exist: not foundexit status 1
```

**Comment by AgustinRamiroDiaz** [comment]
@jmacelroy I'm not able to reproduce the issue anymore, I tried deleting the cache and changing `containerd` versions (`1.6.3, 1.6.1, 1.5.9`). 

To try a more production-like environment, I could try to trigger the circleci job from https://github.com/okteto/buildkit-image and try to use that image instead, to see if the issue arises. 

Any more ideas?

**Comment by AgustinRamiroDiaz** [comment]
I've managed to come across the error again once doing:
1. clean cache
2. downgrade, build a lot
3. upgrade without cleaning
4. build again

I am trying to come up with a more reduced reproducible scenario but this didn't work:
1. downgrade
2. build in main namespace
3. build in new namespace
4. upgrade
5. relaunch app from main namespace
6. relaunch app from previously created namespace namespace

Nor this:
1. downgrade
2. clear cache
3. ok build --no-cache in main namespace
4. upgrade
5. launch app from new namespace

**Comment by AgustinRamiroDiaz** [comment]
I found a scenario that reproduces the error!

1. downgrade
2. delete cache
3. deploy in different namespaces:
    1.	https://github.com/okteto/movies
    1.	https://github.com/okteto/movies-with-compose/
    1.	https://github.com/okteto/microservices-demo-compose
7. upgrade
8. deploy https://github.com/okteto/movies in a new namespace

I'll see tomorrow if I can debug it

**Comment by AgustinRamiroDiaz** [comment]
I've managed to reduce the repro steps

1. downgrade
2. delete cache
3. build from the CLI with `okteto build --no-cache` (I think the --no-cache could be useful for not deleting the cache in the previos step)
    1.	https://github.com/okteto/movies
    1.	https://github.com/okteto/movies-with-compose/
    1.	https://github.com/okteto/microservices-demo-compose
7. upgrade
8. build from the CLI with `okteto build`

**Comment by AgustinRamiroDiaz** [comment]
@jmacelroy  I don't know if it's a viable solution, but seems like clearing buildkit's cache solves the issue 🤔

**Comment by AgustinRamiroDiaz** [comment]
I'll not test this right now, but the `Dockerfile` has `ARG`s for `containerd` versions that could be impacting the behavior (maybe they should match the versions installed from the `go` packages)

**Comment by AgustinRamiroDiaz** [comment]
Update: changing the code to print custom errors, I found that the snapshot error spawns [here](https://github.com/okteto/buildkit/blob/2f455f894c7e5259a574925b47a36720e72888f5/vendor/github.com/containerd/containerd/metadata/snapshot.go#L90)

**Comment by AgustinRamiroDiaz** [comment]
Maybe running rootless in the dev container helps debug the issue:
https://github.com/moby/buildkit/blob/master/docs/rootless.md
https://github.com/rootless-containers/rootlesskit/tree/v0.14.6

**Comment by AgustinRamiroDiaz** [comment]
I've filled an issue in moby's repo: https://github.com/moby/buildkit/issues/2961

**Comment by AgustinRamiroDiaz** [comment]
Adding some prints I've seen that [here](https://github.com/moby/buildkit/blob/c8d25d9a103b70dc300a4fd55e7e576472284e31/cache/metadata/metadata.go#L266) it's searching for `cache.snapshot` in 
```go
map[cache.cachePolicy:0xc000a660c0 cache.createdAt:0xc000a66180 cache.description:0xc000a66240 cache.lastUsedAt:0xc000a66300 cache.recordType:0xc000a663c0 cache.usageCount:0xc000a66450 local.sharedKey:dockerfile:dockerfile::0xc000a66540]
```
and it doesn't find it. I don't know how the `s.values` map is being filled, but it seems like it has a problem with changing versions without deleting cache

**Comment by AgustinRamiroDiaz** [comment]
Digging deeper into the producers and consumers of that map, I found that there are only 2 functions that manipulate the key `cache.snapshot`:
- `getSnapshotID` (consumer [here](https://github.com/okteto/buildkit/blob/40c6d7b9b9c102a527e019fe17b0381a1c09afd2/cache/metadata.go#L254))
- `queueSnapshotID` (producer [here](https://github.com/okteto/buildkit/blob/40c6d7b9b9c102a527e019fe17b0381a1c09afd2/cache/metadata.go#L259))

As we've seen before, the problem arises from a mismatch of assumptions: some function is assuming that the key is in the map when it's actually not there. This assumption seems to be broken by the cache of the previous version because I've tried 2 scenarios:

- a) Upgrade to `v0.10.3` without clearing cache: only **consumes** with `getSnapshotID`
- b) Upgrade to `v0.10.3` clearing cache: **queues** first with `queueSnapshotID` and then **consumes** with `getSnapshotID`

**Comment by AgustinRamiroDiaz** [comment]
> Is there application code that we can write that would detect the current running version and the version last used to create the cache, at which point we could try and delete cache or not? This would be something we'd add to the server startup.

Sounds possible. I'm not that familiarized with the code to know how to manage this, but I've seen a check for the version and the cache managment. The only thing I've missed is a way to detect the previous version that had ran

**Comment by AgustinRamiroDiaz** [comment]
Reading the code I found this [issue](https://github.com/moby/buildkit/pull/2796) that was fixed with [this](https://github.com/moby/buildkit/pull/2796). It might be related to our problem

**Comment by AgustinRamiroDiaz** [comment]
@jmacelroy what do you think about this scenario: 
- create a `v0.10.2` branch from `moby/buildkit` and add it our custom changes
- clear buildkit's cache
- build a bunch of images
- upgrade to this `v0.10.4`
- test if the error arises

This might give us an insight regarding the version upgrade, maybe it's an incompatibility with `v0.9` and not one inside the `v0.10` ones

**Comment by jmacelroy** [comment]
> @jmacelroy what do you think about this scenario:
> 
> * create a `v0.10.2` branch from `moby/buildkit` and add it our custom changes
> * clear buildkit's cache
> * build a bunch of images
> * upgrade to this `v0.10.4`
> * test if the error arises
> 
> This might give us an insight regarding the version upgrade, maybe it's an incompatibility with `v0.9` and not one inside the `v0.10` ones

I think that may be worthwhile long-term but won't address the current issue which is an issue upgrading from v0.9->v0.10. If you ran this scenario and discovered that it's just an issue with upgrading from 0.9->0.10 then I think we would still need a solution for that upgrade. For instance we could reset the cache from 0.9->0.10 but may not need to for 0.10->0.11?

**Comment by AgustinRamiroDiaz** [comment]
> @jmacelroy what do you think about this scenario:
> 
>     * create a `v0.10.2` or `v0.10.1` branch from `moby/buildkit` and add it our custom changes
> 
>     * clear buildkit's cache
> 
>     * build a bunch of images
> 
>     * upgrade to this `v0.10.3`
> 
>     * test if the error arises
> 
> 
> This might give us an insight regarding the version upgrade, maybe it's an incompatibility with `v0.9` and not one inside the `v0.10` ones

Could reproduce this scenario and turns out no errors with the testing I've given it until now. I think this shows the incompatibility between different cache versions of buildkit

**Comment by AgustinRamiroDiaz** [comment]
@jmacelroy @ifbyol I'd appreciate a last quick last eyeballing check to start with the release process 🙏

**Review by jmacelroy — APPROVED** [review]

**Pull request merged**
